# Generated by Django 4.2.3 on 2023-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('dicreption', models.TextField()),
                ('image1', models.ImageField(upload_to='sgp')),
                ('image2', models.ImageField(upload_to='sgp')),
                ('image3', models.ImageField(upload_to='sgp')),
                ('image4', models.ImageField(upload_to='sgp')),
                ('image5', models.ImageField(upload_to='sgp')),
            ],
        ),
    ]
