# Generated by Django 4.2.3 on 2023-07-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='ig',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='im',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='ima',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image4',
            new_name='ime',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image5',
            new_name='img',
        ),
    ]
